;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-delete-char
	c-electric-brace
	c-electric-colon
	c-electric-delete-forward
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	hydra-multiple-cursors/mc/edit-lines
	hydra-multiple-cursors/mc/mark-more-like-this-extended
	org-beginning-of-line
	org-delete-char
	org-end-of-line
	org-kill-line
	org-return
	org-return-indent
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	hydra-multiple-cursors/body
	hydra-multiple-cursors/mc/mark-next-like-this
	hydra-multiple-cursors/mc/mark-previous-like-this
	hydra-multiple-cursors/mc/skip-to-next-like-this
	hydra-multiple-cursors/nil
	org-cycle
	))
